schooloverflow/biostar/forum/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path  # For django versions from 2.0 and up
import debug_toolbar
from biostar.forum import views
from biostar.forum import ajax
from biostar.accounts.urls import account_patterns
from biostar.planet.urls import planet_patterns


forum_patterns = [

    # Main entry. Post listing.
    path('', views.latest, name='post_list'),
    path('admin/', admin.site.urls, name='django_admin'),

    path(r'pages/<str:fname>/', views.pages, name='pages'),

    path('votes/', views.myvotes, name='myvotes'),
    path('bookmarks/', views.bookmarks, name='bookmarks'),
    path('following/', views.following, name='following'),
    path('myposts/', views.myposts, name='myposts'),
    path('mytags/', views.mytags, name='mytags'),
    path('p/<str:uid>/', views.post_view, name='post_view'),
    path('post/search/', views.post_search, name='post_search'),

    path('new/post/', views.new_post, name='post_create'),

    path('b/list/', views.badge_list, name='badge_list'),
    path('t/list/', views.tags_list, name='tags_list'),

    path('b/view/<str:uid>/', views.badge_view, name='badge_view'),

    # Ajax calls
    path('ajax/digest/', ajax.ajax_digest, name='ajax_digest'),
    path('ajax/vote/', ajax.ajax_vote, name='vote'),
    path('ajax/test/', ajax.ajax_test, name='ajax_test'),
    path('ajax/subscribe/', ajax.ajax_subs, name='ajax_sub'),
    path('drag/and/drop/', ajax.drag_and_drop, name='drag_and_drop'),
    path('similar/posts/<str:uid>/', ajax.similar_posts, name='similar_posts'),
    path('ajax/digest/<str:uid>/', ajax.ajax_digest, name='ajax_digest'),
    path('ajax/edit/<str:uid>/', ajax.ajax_edit, name='ajax_edit'),
    path('ajax/comment/create/', ajax.ajax_comment_create, name='ajax_comment_create'),
    path('inplace/form/', ajax.inplace_form, name='inplace_form'),
    path('ajax/user/image/<str:username>/', ajax.user_image, name='user_image'),
    path('similar/posts/<str:uid>/', ajax.similar_posts, name='similar_posts'),
    path('ajax/report/spam/<str:post_uid>/', ajax.report_spam, name='report_spam'),
    path('most/recent/users/', ajax.most_recent_users, name='most_recent_users'),

    path('moderate/<str:uid>/', views.post_moderate, name="post_moderate"),

    # Community urls
    path('community/', views.community_list, name='community_list'),

]


urlpatterns = [

    # Main entry. Post listing.
    path('', include(forum_patterns)),

    # Include the accounts urls
    path('accounts/', include(account_patterns)),

    # Include the planet urls
    path('planet/', include(planet_patterns)),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT, show_indexes=True)

    urlpatterns += [
          path('__debug__/', include(debug_toolbar.urls)),
    ]

schooloverflow/biostar/planet/urls.py
from django.urls import path, include
from biostar.planet import views


planet_patterns = [
    path('', views.blog_list, name="blog_list"),
]
urlpatterns = [

    # Get the reset/ urls
    path(r'', include(planet_patterns)),

]

schooloverflow/biostar/server/urls.py
from django.conf import settings
from django.urls import path, include

from biostar.forum.urls import forum_patterns
from biostar.recipes.urls import recipes_patterns
import biostar.accounts.urls as accounts_urls
from biostar.planet.urls import planet_patterns


urlpatterns = [

    # Mount recipes urls on root.
    path(r'', include(recipes_patterns)),

    # Include forum urls
    path(r'forum/', include(forum_patterns)),

    # Include planets urls
    path(r'planet/', include(planet_patterns)),

    # Include the accounts urls
    path(r'accounts/', include(accounts_urls)),

]

schooloverflow/biostar/urls.py
# Default url patters for the engine.
urlpatterns = []



schooloverflow/biostar/recipes/models.py
import logging

import toml as hjson
import mistune
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.template import loader
from django.urls import reverse
from django.utils import timezone
from django.conf import settings
from biostar.accounts.models import User
from . import util
from .const import *

logger = logging.getLogger("engine")


def join(*args):
    return os.path.abspath(os.path.join(*args))


class Bunch(object):
    def __init__(self, **kwargs):
        self.__dict__.update(kwargs)


def make_html(text, user=None):

    if user and user.profile.trusted:
        html = mistune.markdown(text, escape=False)
    else:
        html = mistune.markdown(text, escape=True)
    return html


def image_path(instance, filename):
    # Name the data by the filename.
    name, ext = os.path.splitext(filename)

    uid = util.get_uuid(6)
    dirpath = instance.get_project_dir()
    imgname = f"images/image-{uid}{ext}"

    # Uploads need to go relative to media directory.
    path = os.path.relpath(dirpath, settings.MEDIA_ROOT)

    imgpath = os.path.join(path, imgname)

    return imgpath


def snippet_images(instance, filename):
    # Name the data by the filename.
    name, ext = os.path.splitext(filename)
    uid = instance.uid or util.get_uuid(6)
    imgname = f"image-{uid}{ext}"

    dirpath = os.path.abspath(os.path.join(settings.MEDIA_ROOT, 'snippets', 'images'))

    # Uploads need to go relative to media directory.
    path = os.path.relpath(dirpath, settings.MEDIA_ROOT)
    imgpath = os.path.join(path, imgname)

    return imgpath


class Manager(models.Manager):

    def get_queryset(self):
        "Regular queries exclude deleted stuff"
        return super().get_queryset().select_related("owner", "owner__profile", "lastedit_user",
                                                     "lastedit_user__profile")


class SnippetType(models.Model):
    image = models.ImageField(default=None, blank=True, upload_to=snippet_images, max_length=MAX_FIELD_LEN)
    uid = models.CharField(max_length=MAX_TEXT_LEN, unique=True)
    # The name referring to this
    name = models.CharField(max_length=MAX_NAME_LEN)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    # Appears to all uses
    default = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.uid = self.uid or util.get_uuid(6)
        super(SnippetType, self).save(*args, **kwargs)


class Snippet(models.Model):
    help_text = models.CharField(max_length=MAX_TEXT_LEN)
    uid = models.CharField(max_length=MAX_TEXT_LEN, unique=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    command = models.CharField(max_length=MAX_TEXT_LEN, null=True)
    # Link a command to one type
    type = models.ForeignKey(SnippetType, on_delete=models.CASCADE)

    # Appears to all uses
    default = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.uid = self.uid or util.get_uuid(6)
        self.owner = self.owner or self.type.owner
        super(Snippet, self).save(*args, **kwargs)


class Project(models.Model):
    PUBLIC, SHAREABLE, PRIVATE = 1, 2, 3
    PRIVACY_CHOICES = [(PRIVATE, "Private"), (SHAREABLE, "Shared"), (PUBLIC, "Public")]

    # Rank in a project list.
    rank = models.FloatField(default=100)

    # The user that edited the object most recently.
    lastedit_user = models.ForeignKey(User, related_name='proj_editor', null=True, on_delete=models.CASCADE)
    lastedit_date = models.DateTimeField(default=timezone.now)

    # Limits who can access the project.
    privacy = models.IntegerField(default=PRIVATE, choices=PRIVACY_CHOICES)
    image = models.ImageField(default=None, blank=True, upload_to=image_path, max_length=MAX_FIELD_LEN)
    name = models.CharField(default="New Project", max_length=MAX_NAME_LEN)
    deleted = models.BooleanField(default=False)

    # We need to keep the owner.
    owner = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    text = models.TextField(default='Project description.', max_length=MAX_TEXT_LEN)

    html = models.TextField(default='html', max_length=MAX_LOG_LEN)
    date = models.DateTimeField(auto_now_add=True)
    # Internal uid that is not editable.
    uid = models.CharField(max_length=32, unique=True)
    # Unique project label that is editable.
    #TODO: being refactored out.
    label = models.CharField(max_length=32, unique=True, null=True)

    # FilePathField points to an existing project directory.
    dir = models.FilePathField(max_length=MAX_FIELD_LEN, default='')

    sharable_token = models.CharField(max_length=32, null=True, unique=True)

    data_count = models.IntegerField(default=0, null=True, db_index=True)
    recipes_count = models.IntegerField(default=0, null=True, db_index=True)
    jobs_count = models.IntegerField(default=0, null=True, db_index=True)

    objects = Manager()

    def save(self, *args, **kwargs):
        now = timezone.now()
        self.date = self.date or now
        self.sharable_token = self.sharable_token or util.get_uuid(30)
        self.html = make_html(self.text, user=self.lastedit_user)
        self.name = self.name[:MAX_NAME_LEN]
        self.uid = self.uid or util.get_uuid(8)
        self.label = self.label or self.uid or util.get_uuid(8)
        self.lastedit_user = self.lastedit_user or self.owner
        self.lastedit_date = now

        super(Project, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def uid_is_set(self):
        assert bool(self.uid.strip()), "Sanity check. UID should always be set."

    def url(self):
        self.uid_is_set()
        return reverse("project_view", kwargs=dict(uid=self.uid))

    def get_project_dir(self):
        return self.dir

    def get_data_dir(self):
        "Match consistency of data dir calls"
        return self.get_project_dir()

    def set_counts(self, save=True):
        """
        Set the data, recipe, and job count for this project
        """
        data_count = self.data_set.filter(deleted=False).count()
        recipes_count = self.analysis_set.filter(project=self, deleted=False).count()
        job_count = self.job_set.filter(deleted=False).count()

        Project.objects.filter(id=self.id).update(data_count=data_count, recipes_count=recipes_count,
                                                  jobs_count=job_count)

    @property
    def is_public(self):
        return self.privacy == self.PUBLIC

    @property
    def is_private(self):
        return self.privacy == self.PRIVATE

    @property
    def project(self):
        return self

    @property
    def json_text(self):
        return hjson.dumps(self.json_data)

    @property
    def json_data(self):
        payload = dict(
            settings=dict(
                uid=self.uid,
                name=self.name,
                image=f"{'_'.join(self.name.split())}-{self.pk}.png",
                privacy=dict(self.PRIVACY_CHOICES)[self.privacy],
                help=self.text,
                url=settings.BASE_URL,
                project_uid=self.uid,
                id=self.pk,

                ),
            recipes=[recipe.uid for recipe in self.analysis_set.all()])

        return payload

    @property
    def summary(self):
        """
        Returns first line of text
        """
        lines = self.text.splitlines() or ['']
        first = lines[0]
        return first

    @property
    def is_shareable(self):
        return self.privacy == self.SHAREABLE

    def get_sharable_link(self):

        # Return a sharable link if the project is shareable
        if self.is_shareable:
            return reverse('project_share', kwargs=dict(token=self.sharable_token))

        return '/'

    def get_name(self):
        if self.deleted:
            return f'Deleted: {self.name}'

        return self.name


class Access(models.Model):
    """
    Allows access of users to Projects.
    """
    NO_ACCESS, READ_ACCESS, WRITE_ACCESS, SHARE_ACCESS = 1, 2, 3, 4
    ACCESS_CHOICES = [
        (NO_ACCESS, "No Access"),
        (READ_ACCESS, "Read Access"),
        (WRITE_ACCESS, "Write Access"),
        (SHARE_ACCESS, "Share Access"),
    ]

    ACCESS_MAP = dict(ACCESS_CHOICES)

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    access = models.IntegerField(default=NO_ACCESS, choices=ACCESS_CHOICES, db_index=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} on {self.project.name}"

    def save(self, *args, **kwargs):
        super(Access, self).save(*args, **kwargs)


@receiver(post_save, sender=Project)
def update_access(sender, instance, created, raw, update_fields, **kwargs):
    # Give the owner WRITE ACCESS if they do not have it.
    entry = Access.objects.filter(user=instance.owner, project=instance, access=Access.WRITE_ACCESS)
    if entry.first() is None:
        entry = Access.objects.create(user=instance.owner, project=instance, access=Access.WRITE_ACCESS)


class Data(models.Model):
    PENDING, READY, ERROR, = 1, 2, 3
    STATE_CHOICES = [(PENDING, "Pending"), (READY, "Ready"), (ERROR, "Error")]
    state = models.IntegerField(default=PENDING, choices=STATE_CHOICES)

    LINK, UPLOAD, TEXTAREA = 1, 2, 3
    METHOD_CHOICE = [(LINK, "Linked Data"), (UPLOAD, "Uploaded Data"), (TEXTAREA, "Text Field")]
    method = models.IntegerField(default=LINK, choices=METHOD_CHOICE)

    name = models.CharField(max_length=MAX_NAME_LEN, default="My Data")
    image = models.ImageField(default=None, blank=True, upload_to=image_path, max_length=MAX_FIELD_LEN)

    deleted = models.BooleanField(default=False)

    # Rank on a data list.
    rank = models.FloatField(default=100)

    # The user that edited the object most recently.

schooloverflow/biostar/recipes/templates/admin_index.html
{% extends "base_listing.html" %}
{% load engine_tags %}

{% block headtitle %}
    Site Admin
{% endblock %}

{% block title %}
    <i class="dashboard icon"></i> Site Admin
{% endblock %}


{% block content %}

    {% show_messages messages %}


        <div class="ui vertical segment">

            <div class="ui header">
                <a href="{% url 'admin:index' %}">
                    <i class="desktop icon"></i>Django Admin
                </a>
            </div>

        </div>

        <div class="ui vertical segment">
            <div class="ui header">
                All jobs
            </div>
            <div class="ui divided list">
                <table class="ui celled selectable striped compact table">
                    <thead>
                    <tr>

                        <th>Status</th>
                        <th>Name</th>
                        <th>Project</th>
                        <th>User</th>
                        <th>Start Date</th>
                    </tr>
                    </thead>

                    <tbody>

                    {% for job in jobs %}
                        <tr >
                            <td style="padding: 1px;text-align: center;">
                                <div class="ui {% job_color job %} label">{{ job.get_state_display }}</div>
                            </td>
                            <td class="{% if job.deleted %}negative{% endif %}">
                                <a href="{{ job.url }}">{{ job.get_name|truncatechars:40  }}</a>
                            </td>

                            <td>
                                <a href="{{ job.project.url }}">{{ job.project.get_name|truncatechars:40 }}</a>
                            </td>
                           <td>
                                <a href="{{ job.owner.profile.get_absolute_url }}">{{ job.owner.profile.name }}</a>
                            </td>

                            <td>
                                {% if job.start_date %}{{ job.start_date }}{% else %} Not Started
                                {% endif %}
                            </td>

                        </tr>
                    {% endfor %}

                    </tbody>

                </table>


            </div>
        </div>



{% endblock %}

schooloverflow/biostar/recipes/templates/base_content.html
{% extends "engine_base.html" %}
{% load engine_tags %}
{% load static %}

{% block headtitle %}
    {{ project.get_name }}
{% endblock %}


{% block body %}
    <input type="hidden" id="project_id" value="{{ project.id }}">

    <div class="ui center aligned basic vertical segment">
        <div class="ui large header">
            <img class="ui avatar image" src="{% img project %}"/> {{ project.name }}
        </div>
    </div>

    <a class="ui left ribbon projects label" href="{% url 'project_list' %}">
        <i class="database icon"></i> All Projects
    </a>

    <span id="clipboard"></span>

    {% block ribbon %}
        {% if user.is_authenticated %}
            <a class="ui right ribbon obj label" href="{% url 'recipe_create' project.uid %}">
                <i class="plus icon"></i>New Recipe
            </a>
        {% endif %}
    {% endblock %}

    <div class="ui basic segment" >

    <div class="ui top attached large tabular  menu">


        <a class="{% activate 'info' active %}  item" href="{% url 'project_viewing' project.label %}">
            <i class="info circle icon"></i><span class="phone">Project </span>
        </a>

        <a class="{% activate 'data' active %}  item" href="{% url 'data_listing' project.label %}">
            <i class="file text icon"></i><span id="data_count">{{ data_count }}</span>&nbsp;<span
                class="phone"> Data</span>
        </a>
        <a class="{% activate 'recipes' active %}  item" href="{% url 'recipe_listing' project.label %}">
            <i class="settings icon"></i> {{ recipe_count }}&nbsp;<span class="phone"> Recipes</span>
        </a>

        <a class="{% activate 'jobs' active %} item" href="{% url 'job_listing' project.label %}">
            <i class="bar chart icon"></i><span id="job_count">{{ result_count }}</span><span class="phone">&nbsp;Results</span>
        </a>

        {% if activate %}
            <div class="active item" id="job_item">
                <i class="angle double down icon"></i> <span class="tablet">{{ activate }}</span>
            </div>
        {% endif %}

    </div>


    {% block contain %}
        <div class="ui bottom attached large segment">

            {% show_messages messages %}
            {% block content %}
                Content
            {% endblock %}

        </div>
    {% endblock %}



{% endblock %}

schooloverflow/biostar/recipes/templates/data_edit.html
{% extends "base_content.html" %}
{% load engine_tags %}

{% block headtitle %}
    Edit Data: {{ data.name }}
{% endblock %}
{% block ribbon %}
    {% if user.is_authenticated %}
        <a class="ui right ribbon obj label" href="{% url 'data_upload' project.uid %}">
           <i class="plus icon"></i> New Data </a>
    {% endif %}
{% endblock %}

{% block content %}
<div class="narrow">

    <div class="ui raised segment inputcolor">
    {% form_errors form %}
        <form method="post" class="ui form" action="{% url 'data_edit' data.uid %}" enctype="multipart/form-data">

            {% csrf_token %}

            <div class="field segment">
                <label>Name</label>
                {{ form.name }}
                <p class="muted">Edit the data name</p>
            </div>

            <div class="field">

                {% if form.file %}
                    {{ form.media }}
                    <label>File</label>
                    {{form.file}}
                    <p class="muted">Replace content of stored file with this one. <b>This does not change the name.</b></p>

                {% elif form.input_text %}
                    <label>Input Text</label>
                    <textarea rows="10" cols="55" name="{{form.input_text.name}}" id="id_{{form.input_text.name}}"
                          maxlength="{{ form.input_text.field.max_length }}">{% if form.input_text.value %}{{ form.input_text.value }}{% endif %}</textarea>
                    <p class="muted">Edit uploaded text ( {{ form.input_text.field.max_length }} characters ).</p>
                {% endif %}

            </div>
            <div class="ui small horizontal divider header">
            <i class="ui pen square icon"></i>Extra Information
            </div>

            <div class="field">
                <label>Data Type</label>
                {{ form.type }}
                <p class="muted">Data type used to sub-select during analysis.</p>
            </div>

            <div class="field segment">
                <label>Data description</label>
                {{ form.text }}
                <p class="muted">A detailed explanation of what is in the data collection (markdown OK).</p>
            </div>

            <button type="submit" class="ui submit green button">
                <i class="save icon"></i>Save
            </button>
            <a class="ui right floated button" href="{% url 'data_view' data.uid %}">
                <i class="undo icon"></i>Cancel
            </a>

        </form>
    </div>

{% endblock %}

schooloverflow/biostar/recipes/templates/data_list.html
{% extends "base_content.html" %}
{% load engine_tags %}

{% block headtitle %}
    Data List
{% endblock %}


{% block ribbon %}

    {% if user.is_authenticated %}

        <a class="ui right ribbon obj label" href="{% url 'data_upload' project.uid %}">
           <i class="plus icon"></i> New Data </a>
    {% endif %}

{% endblock %}

{% block contain %}


    <div class="ui bottom attached segment">

        {% show_messages messages %}

        <div class="ui large vertical segment">
            <div class="ui divided items">

                {% for data in data_list %}

                    <div class="item data" data-value="{{ data.uid }}" >

                        <div class="content">
                            <a class="subheader" href="{% url 'data_view' data.uid %}">
                                {% if job.deleted %}Deleted: {% endif %}
                                <i class="file icon"></i>{{ data.name }}
                            </a>
                            <div class="meta">
                                <div class="ui small labels">
                                    {% size_label data %}
                                    {% type_label data %}
                                    {% created_by date=data.lastedit_date user=data.owner %}
                                </div>
                            </div>
                            <div class="meta">{{ data.summary|safe }}</div>

                        </div>

                        {% if request.user.is_authenticated %}

                            <div class="ui mini buttons">
                                <a class="ui right floated button copy">
                                    <i class="copy icon"></i>Copy
                                </a>
                                <div class="or"></div>
                                <a class="ui right floated button delete">
                                    <i class="trash icon"></i> <span class="fitme">Delete</span>
                                </a>
                            </div>

                        {% endif %}

                    </div>

                {% empty %}
                    <div class="item ">
                        <div class="ui warning message"><i class="ui info circle icon"></i>This project does not yet
                            contain data.
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </div>


{% endblock %}

schooloverflow/biostar/recipes/templates/data_view.html
{% extends "base_content.html" %}
{% load engine_tags %}


{% block headtitle %}
    {{ data.name }}
{% endblock %}
{% block ribbon %}
    {% if user.is_authenticated %}

        <a class="ui right ribbon obj label" href="{% url 'data_upload' project.uid %}">
           <i class="plus icon"></i> New Data </a>
    {% endif %}
{% endblock %}
{% block content %}
<div class="data" data-value="{{ data.uid }}">

    <div class="ui large vertical segment">

        <div class="ui divided items">

            <div class="item">
                <div class="content">

                    <a class="subheader" href="{% url 'data_view' data.uid %}">
                        <i class="file icon"></i>Data: {{ data.get_name }}
                    </a>

                    <div class="meta">
                        <div class="ui small labels">
                            {% size_label data %}
                            {% type_label data %}
                            {%  created_by date=data.lastedit_date user=data.owner %}
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>


    <div class="ui large vertical segment">

        <div class="six ui small buttons">
            <a class="ui button" href="{% url 'data_edit' data.uid %}">
                <i class="edit icon"></i> <span class="tablet">Edit Data</span>
            </a>

            <a class="ui copy button">
                <i class="copy icon"></i>Copy Data
            </a>
            <a class="ui button tablet" href="{% url 'data_delete' data.uid %}">
                <i class="trash icon"></i> <span class="tablet">Delete Data</span>
            </a>


        </div>
    </div>
</div>
    <div class="ui vertical large segment">
        <div class="ui aligned header">Data List</div>
        <div>Files contained in the dataset</div>
        {% include 'widgets/files_list.html' %}
    </div>

    {% if data.html %}
        <div class="ui vertical large segment">
            <div class="ui aligned header">Data Info</div>
            <div>{{ data.html|safe }}</div>
        </div>
    {% endif %}

    <div class="ui vertical large segment">
        <div class="ui aligned header">Data Content</div>
        <pre>{{ data.peek }}</pre>
    </div>


{% endblock %}

schooloverflow/biostar/recipes/templates/import_files.html
{% extends "base_listing.html" %}
{% load engine_tags %}

{% block headtitle %}
    Project List
{% endblock %}

{% block title %}
    <i class="download icon"></i> Data Import
{% endblock %}


{% block content %}

    {% show_messages messages %}

    {% include 'widgets/files_list.html' %}

{% endblock %}

schooloverflow/biostar/recipes/templates/project_info.html
{% extends "base_content.html" %}
{% load engine_tags %}

{% block headtitle %}
    Data List
{% endblock %}

{% block ribbon %}
    {% if user.is_authenticated %}
        <a class="ui right ribbon obj label" href="{% url 'project_create' %}">
            <i class="plus icon"></i>New Project
        </a>
    {% endif %}
{% endblock %}

{% block content %}
    <div>

        <h3 class="ui header">Project Information</h3>
        {{ project.html|safe }}
        <div class="muted">
            <span class="ui label">{{ project.get_privacy_display }}</span>
            Project owned by <a href="{% url 'user_profile'  project.owner.profile.uid %}">
            {{ project.owner.profile.name }}
        </a>&bull;
            {% created_by date=project.lastedit_date user=project.lastedit_user %}

        </div>

        {% if project.is_shareable and project.owner == request.user %}
            <div class="ui divider"></div>

            <div class="ui compact message"><i class="warning icon"></i>Any user with this link gains <b>Share
                Access</b> to this project.
            </div>
            <div>
                <code><a href="{% url 'project_share' project.sharable_token %}">
                    {% full_url %}{% url 'project_share' project.sharable_token %}</a>
                </code>
            </div>

        {% endif %}


        {% if write_access %}
            <div class="ui  divider"></div>
            <div class="ui three small buttons">

                <a class="ui  button" href="{% url 'project_edit' project.uid %}">
                    <i class="edit icon"></i>Edit Project
                </a>

                <a class="ui  button" href="{% url 'project_users' project.uid %}">
                    <i class="users icon"></i>Manage Access
                </a>


                <a class="ui button tablet" href="{% url 'project_delete' project.uid %}">
                    {% if project.deleted %}
                        <i class="undo icon"></i> <span class="tablet">Restore Project</span>
                    {% else %}
                        <i class="trash icon"></i> <span class="tablet">Delete Project</span>
                    {% endif %}
                </a>

            </div>

        {% endif %}
    </div>
{% endblock %}

schooloverflow/biostar/recipes/templates/project_list.html
{% extends "base_listing.html" %}
{% load engine_tags %}
{% load static %}

{% block headtitle %}
    Project List
{% endblock %}

{% block title %}
    <i class="file icon"></i> Project list
{% endblock %}


{% block content %}

    {% show_messages messages %}

    <div class="ui divided items">
        {% for project in projects %}
            <div class="item">

                <img class="ui mytiny circular fancy image" src="{% img project %}"/>

                <div class="content">

                    <a class="subheader" href="{% url 'recipe_listing' project.label %}">
                        <i class="database icon"></i>{{ project.get_name }}
                    </a>

                    <div class="meta">{{ project.summary|markdown|safe }} </div>

                    <div class="extra">

                        <span class="ui label">{{ project.get_privacy_display }}</span>

                        <a href="{% url 'data_listing' project.label %}">
                            <i class="file text icon"></i>{{ project.data_count }} data</a>&bull;

                        <a href="{% url 'recipe_listing' project.label %}">
                            <i class="setting icon"></i>{{ project.recipes_count }}
                            recipe{{ project.recipes_count|pluralize }}</a>&bull;

                        <a href="{% url 'job_listing' project.label %}">
                            <i class="bar chart icon"></i>{{ project.jobs_count }}
                            result{{ project.jobs_count|pluralize }}</a>

                        {% created_by date=project.lastedit_date user=project.lastedit_user %}

                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    {% if not projects %}
        <div class="item ">
<<<<<<< HEAD
            <div class="ui warning message"><i class="ui warning circle icon"></i>There are no projects yet.</div>
=======
            <div class="ui warning message"><i class="ui warning circle icon"></i>No projects at this time.</div>
>>>>>>> 71577cf09291ba94bc2a1474793221f5560012df
        </div>
    {% endif %}

{% endblock %}

schooloverflow/biostar/recipes/templates/recipe_run.html
{% extends "base_content.html" %}
{% load engine_tags %}

{% block headtitle %}
    {{ recipe.name }}
{% endblock %}

{% block title %}
    Run {{ recipe.name }}
{% endblock %}

{% block content %}
    {% include "parts/recipe_run.html" %}
{% endblock %}