schooloverflow/biostar/forum/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path  # For django versions from 2.0 and up
import debug_toolbar
from biostar.forum import views
from biostar.forum import ajax
from biostar.accounts.urls import account_patterns
from biostar.planet.urls import planet_patterns


forum_patterns = [

    # Main entry. Post listing.
    path('', views.latest, name='post_list'),
    path('admin/', admin.site.urls, name='django_admin'),

    path(r'pages/<str:fname>/', views.pages, name='pages'),

    path('votes/', views.myvotes, name='myvotes'),
    path('bookmarks/', views.bookmarks, name='bookmarks'),
    path('following/', views.following, name='following'),
    path('myposts/', views.myposts, name='myposts'),
    path('mytags/', views.mytags, name='mytags'),
    path('p/<str:uid>/', views.post_view, name='post_view'),
    path('post/search/', views.post_search, name='post_search'),

    path('new/post/', views.new_post, name='post_create'),

    path('b/list/', views.badge_list, name='badge_list'),
    path('t/list/', views.tags_list, name='tags_list'),

    path('b/view/<str:uid>/', views.badge_view, name='badge_view'),

    # Ajax calls
    path('ajax/digest/', ajax.ajax_digest, name='ajax_digest'),
    path('ajax/vote/', ajax.ajax_vote, name='vote'),
    path('ajax/test/', ajax.ajax_test, name='ajax_test'),
    path('ajax/subscribe/', ajax.ajax_subs, name='ajax_sub'),
    path('drag/and/drop/', ajax.drag_and_drop, name='drag_and_drop'),
    path('similar/posts/<str:uid>/', ajax.similar_posts, name='similar_posts'),
    path('ajax/digest/<str:uid>/', ajax.ajax_digest, name='ajax_digest'),
    path('ajax/edit/<str:uid>/', ajax.ajax_edit, name='ajax_edit'),
    path('ajax/comment/create/', ajax.ajax_comment_create, name='ajax_comment_create'),
    path('inplace/form/', ajax.inplace_form, name='inplace_form'),
    path('ajax/user/image/<str:username>/', ajax.user_image, name='user_image'),
    path('similar/posts/<str:uid>/', ajax.similar_posts, name='similar_posts'),
    path('ajax/report/spam/<str:post_uid>/', ajax.report_spam, name='report_spam'),
    path('most/recent/users/', ajax.most_recent_users, name='most_recent_users'),

    path('moderate/<str:uid>/', views.post_moderate, name="post_moderate"),

    # Community urls
    path('community/', views.community_list, name='community_list'),

]


urlpatterns = [

    # Main entry. Post listing.
    path('', include(forum_patterns)),

    # Include the accounts urls
    path('accounts/', include(account_patterns)),

    # Include the planet urls
    path('planet/', include(planet_patterns)),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT, show_indexes=True)

    urlpatterns += [
          path('__debug__/', include(debug_toolbar.urls)),
    ]

schooloverflow/biostar/planet/urls.py
from django.urls import path, include
from biostar.planet import views


planet_patterns = [
    path('', views.blog_list, name="blog_list"),
]
urlpatterns = [

    # Get the reset/ urls
    path(r'', include(planet_patterns)),

]

schooloverflow/biostar/server/urls.py
from django.conf import settings
from django.urls import path, include

from biostar.forum.urls import forum_patterns
from biostar.recipes.urls import recipes_patterns
import biostar.accounts.urls as accounts_urls
from biostar.planet.urls import planet_patterns


urlpatterns = [

    # Mount recipes urls on root.
    path(r'', include(recipes_patterns)),

    # Include forum urls
    path(r'forum/', include(forum_patterns)),

    # Include planets urls
    path(r'planet/', include(planet_patterns)),

    # Include the accounts urls
    path(r'accounts/', include(accounts_urls)),

]

schooloverflow/biostar/urls.py
# Default url patters for the engine.
urlpatterns = []



schooloverflow/biostar/accounts/models.py
import uuid
from datetime import datetime, timedelta

import mistune
from django.conf import settings
from django.shortcuts import reverse
from django.contrib.auth.models import User
from django.db import models
from django.utils.timezone import utc
from biostar.accounts import util


def fixcase(name):
    return name.upper() if len(name) == 1 else name.lower()


def now():
    return datetime.utcnow().replace(tzinfo=utc)


MAX_UID_LEN = 255
MAX_NAME_LEN = 255
MAX_TEXT_LEN = 10000
MAX_FIELD_LEN = 1024


class ProfileManager(models.Manager):

    def valid_users(self):
        """
        Return valid user queryset, filtering new and trusted users.
        """

        # Filter for new or trusted users.
        query = super().get_queryset().filter(models.Q(state=Profile.TRUSTED) | models.Q(state=Profile.NEW))

        return query


class Profile(models.Model):
    NEW, TRUSTED, SUSPENDED, BANNED, SPAMMER = range(5)
    STATE_CHOICES = [(NEW, "Neu"), (TRUSTED, "Aktiv"), (SPAMMER, "Spammer"),
                     (SUSPENDED, "Unaktiv"), (BANNED, "Banned")]
    state = models.IntegerField(default=NEW, choices=STATE_CHOICES, db_index=True)

    SCHUELER, LEHRER, MANAGER = range(3)
    ROLE_CHOICES = [
        (SCHUELER, "Schüler"), (LEHRER, "Lehrer"), (MANAGER, "Admin")
    ]

    NO_DIGEST, DAILY_DIGEST, WEEKLY_DIGEST, MONTHLY_DIGEST, ALL_MESSAGES = range(5)

    DIGEST_CHOICES = [(NO_DIGEST, 'Nie'), (DAILY_DIGEST, 'Täglich'),
                      (WEEKLY_DIGEST, 'Wöchentlich'), (MONTHLY_DIGEST, 'Monatlich'),
                      (ALL_MESSAGES, "Email für jeden neuen Eintrag (mailing list mode)")
                      ]
    # Subscription to daily and weekly digests.
    digest_prefs = models.IntegerField(choices=DIGEST_CHOICES, default=WEEKLY_DIGEST)

    LOCAL_MESSAGE, EMAIL_MESSAGE, NO_MESSAGES, DEFAULT_MESSAGES = range(4)
    MESSAGING_TYPE_CHOICES = [
        (DEFAULT_MESSAGES, "Default"),
        (EMAIL_MESSAGE, "Email"),
        (LOCAL_MESSAGE, "Local Messages"),
        (NO_MESSAGES, "No messages"),

    ]
    # Default subscriptions inherit from this
    message_prefs = models.IntegerField(choices=MESSAGING_TYPE_CHOICES, default=DEFAULT_MESSAGES)

    # Connection to the user.
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # User unique id (handle)
    uid = models.CharField(max_length=MAX_UID_LEN, unique=True)

    # User diplay name.
    name = models.CharField(max_length=MAX_NAME_LEN, default='', db_index=True)

    # Maximum amount of uploaded files a user is allowed to aggregate, in mega-bytes.
    max_upload_size = models.IntegerField(default=0)

    # The role of the user.
    role = models.IntegerField(default=SCHUELER, choices=ROLE_CHOICES)

    # The date the user last logged in.
    last_login = models.DateTimeField(null=True, max_length=255, db_index=True)

    # The number of new messages for the user.
    new_messages = models.IntegerField(default=0, db_index=True)

    # The last visit by the user.
    date_joined = models.DateTimeField(auto_now_add=True, max_length=255)

    # User provided location.
    location = models.CharField(default="", max_length=255, blank=True, db_index=True)

    # User provided website.
    website = models.URLField(default="", max_length=255, blank=True)

    # Google scholar ID
    #scholar = models.CharField(default="", max_length=255, blank=True)

    # User reputation score.
    score = models.IntegerField(default=0, db_index=True)

    # Twitter ID
    #twitter = models.CharField(default="", max_length=255, blank=True)

    # This field is used to select content for the user.
    my_tags = models.CharField(default="", max_length=MAX_TEXT_LEN, blank=True)

    # The tag value is the canonical form of the post's tags
    watched_tags = models.CharField(max_length=MAX_TEXT_LEN, default="", blank=True)

    # Description provided by the user html.
    text = models.TextField(default="No profile information", null=True, max_length=MAX_TEXT_LEN, blank=True)

    # The html version of the user information.
    html = models.TextField(null=True, max_length=MAX_TEXT_LEN, blank=True)

    # The state of the user email verfication.
    email_verified = models.BooleanField(default=False)

    # Automatic notification
    notify = models.BooleanField(default=False)

    # Opt-in to all messages from the site
    opt_in = models.BooleanField(default=False)

    objects = ProfileManager()

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.uid = self.uid or util.get_uuid(8)
        self.html = self.html or mistune.markdown(self.text)
        self.max_upload_size = self.max_upload_size or self.get_upload_size()
        self.name = self.name or self.user.first_name or self.user.email.split("@")[0]
        self.date_joined = self.date_joined or now()
        self.last_login = self.last_login or now() #- timedelta(days=1)
        super(Profile, self).save(*args, **kwargs)

    @property
    def state_dict(self):
        return dict(self.STATE_CHOICES)

    def get_upload_size(self):

        # Admin users upload limit
        if self.user.is_superuser or self.user.is_staff:
            return settings.ADMIN_UPLOAD_SIZE
        # Trusted users upload limit
        if self.user.profile.trusted:
            return settings.TRUSTED_UPLOAD_SIZE

        # Get the default upload limit
        return settings.MAX_UPLOAD_SIZE

    def require_recaptcha(self):
        """Check to see if this user requires reCAPTCHA"""
        is_required = not (self.trusted or self.score > settings.RECAPTCHA_THRESHOLD_USER_SCORE)
        return is_required

    def get_score(self):
        """
        """
        score = self.score * 10
        return score

    @property
    def is_moderator(self):
        # Managers can moderate as well.
        return self.role == self.LEHRER or self.role == self.MANAGER or self.user.is_staff or self.user.is_superuser

    @property
    def trusted(self):
        return (self.user.is_staff or self.state == self.TRUSTED or
                self.role == self.LEHRER or self.role == self.MANAGER or self.user.is_superuser)

    @property
    def is_manager(self):
        return self.role == self.MANAGER

    def get_absolute_url(self):

        return reverse('user_profile', kwargs=dict(uid=self.uid))

    @property
    def is_suspended(self):
        return self.state == self.SUSPENDED

    @property
    def is_banned(self):
        return self.state == self.BANNED

    @property
    def is_spammer(self):
        return self.state == self.SPAMMER

    @property
    def is_valid(self):
        """
        User is not banned, suspended, or banned
        """
        return not self.is_spammer and not self.is_suspended and not self.is_banned

    @property
    def recently_joined(self):
        """
        User that joined X amount of days are considered new.
        """
        recent = (util.now() - self.date_joined).days > settings.RECENTLY_JOINED_DAYS
        return recent

    @property
    def low_rep(self):
        """
        User has a low score
        """
        return self.score <= settings.LOW_REP_THRESHOLD and not self.is_moderator


class Logger(models.Model):
    # Put in delte
    MODERATING, CREATION, EDIT, LOGIN, LOGOUT, BROWSING = range(6)

    ACTIONS_CHOICES = [(MODERATING, "Preformed a moderation action."),
                       (CREATION, "Created an object."),
                       (EDIT, "Edited an object."),
                       (LOGIN, "Logged in to the site."),
                       (LOGOUT, "Logged out of the site."),
                       (BROWSING, "Browsing the site.")]

    # User that preformed this action
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    # Action this user is took.
    action = models.IntegerField(choices=ACTIONS_CHOICES, default=BROWSING)

    # Stores the specific log text
    log_text = models.TextField(default='')

    # Date this log was created
    date = models.DateTimeField(auto_now_add=True)


# Connects user to message bodies
class MessageBody(models.Model):
    """
    A message that may be shared across all users.
    """
    body = models.TextField(max_length=MAX_TEXT_LEN)
    html = models.TextField(default='', max_length=MAX_TEXT_LEN * 10)

    def save(self, *args, **kwargs):
        self.html = self.html or mistune.markdown(self.body)
        super(MessageBody, self).save(**kwargs)


# Connects user to message bodies
class Message(models.Model):
    """
    Connects recipients to sent messages
    """

    SPAM, VALID, UNKNOWN = range(3)
    SPAM_CHOICES = [(SPAM, "Spam"), (VALID, "Not spam"), (UNKNOWN, "Unknown")]
    spam = models.IntegerField(choices=SPAM_CHOICES, default=UNKNOWN)

    uid = models.CharField(max_length=32, unique=True)
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="author", on_delete=models.CASCADE)
    recipient = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    subject = models.CharField(max_length=120)
    body = models.ForeignKey(MessageBody, on_delete=models.CASCADE)

    unread = models.BooleanField(default=True)
    sent_date = models.DateTimeField(db_index=True, null=True)

    def save(self, *args, **kwargs):
        self.uid = self.uid or util.get_uuid(10)
        self.sent_date = self.sent_date or util.now()
        super(Message, self).save(**kwargs)

    def __str__(self):
        return f"Message {self.sender}, {self.recipient}"

    def css(self):
        return 'new' if self.unread else ''

schooloverflow/biostar/forum/templates/accounts/edit_profile.html
{% extends "forum_base.html" %}
{% load forum_tags %}
{% load accounts_tags %}

{% block headtitle %}Edit Profile{% endblock %}

{% block content %}

    <div class="ui horizontal segments no-shadow">

        <div class="ui segment  no-shadow"></div>
        <div class="ui basic compact segment no-shadow">

            <form method="post" class="ui equal width form" action="{% url 'edit_profile' %}">
                {{ form.media }}
                {% csrf_token %}

                {% form_errors form %}

                <div class="ui basic center aligned segment">
                    <span class="ui header">Update Profile</span>
                </div>

                <div class="fields">
                    <div class="empty form-field field"></div>

                    <div class="required form-field field">
                        <div class="ui form-wrap segment">
                            <label><i class="address card icon"></i>Name </label>
                            {{ form.name }}
                            <div class="muted">
                                Displayed name
                            </div>
                        </div>
                    </div>

                    <div class="empty form-field field"></div>
                </div>

                <div class="fields">
                    <div class="empty form-field field"></div>

                    <div class="required form-field field">
                        <div class="ui form-wrap segment">
                            <label><i class="at icon"></i>Handle</label>
                            {{ form.username }}
                            <div class="muted">
                                Handle may be used to reference you in posts.
                            </div>
                        </div>
                    </div>

                    <div class="empty form-field field"></div>
                </div>
                <div class="fields">
                    <div class="empty form-field field"></div>

                    <div class="required form-field field">
                        <div class="ui form-wrap segment">
                            <label><i class="envelope icon"></i>Email</label>
                            {{ form.email }}
                            <div class="muted">
                                Email used to register to the site.
                            </div>
                        </div>
                    </div>

                    <div class="empty form-field field"></div>
                </div>

                <div class="fields">

                    <div class="field">
                        <div class="ui form-wrap segment">
                            <label><i class="linkify icon"></i>Website</label>
                            {{ form.website }}
                            <div class="muted">
                                URL to your website
                            </div>
                        </div>
                    </div>

                    <div class="field">
                        <div class="ui form-wrap segment">
                            <label><i class="map marker alternate icon"></i>Location</label>
                            {{ form.location }}
                            <div class="muted">
                                Country/City/Institution
                            </div>
                        </div>
                    </div>


                </div>


                <div class="fields">
                    <div class="field">
                        <div class="ui form-wrap segment">

                            <label><i class="twitter icon"></i>Twitter id</label>
                            {{ form.twitter }}
                            <div class="muted">
                                Your twitter id
                            </div>
                        </div>
                    </div>

                    <div class="field">
                        <div class="ui form-wrap segment">
                            <label><i class="google icon"></i>Scholar</label>
                            {{ form.scholar }}
                            <div class="muted">
                                Your Google Scholar ID
                            </div>
                        </div>
                    </div>
                </div>

                <div class="fields">

                    <div class="field">
                        <div class="ui form-wrap segment" style="display: grid">
                            <label><i class="bell icon"></i>Notifications </label>
                            {{ form.message_prefs }}
                            <div class="muted">
                                {{ form.message_prefs.help_text }}
                            </div>
                        </div>
                    </div>

                </div>

                <div class="fields">
                    <div class="field">
                        <div class="ui form-wrap segment" style="display: grid">
                            <label><i class="tags icon"></i>My Tags </label>

                            {% tags_field form_field=form.my_tags initial=user.profile.my_tags %}

                            <div class="muted">
                                Post with tags listed here will show up in the My Tags tab.
                                Example: <code>galaxy</code>, <code>bed</code>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="fields">
                    <div class="field">
                        <div class="ui form-wrap segment" style="display: grid">
                            <label><i class="tags icon"></i>Watched Tags </label>

                            {% tags_field form_field=form.watched_tags initial=user.profile.watched_tags %}

                            <div class="muted">
                                Get email when a post matching the tag is posted.
                                Example: <code>minia</code>, <code>bedops</code>, <code>breakdancer</code>,
                                <code>music</code>.
                            </div>
                        </div>
                    </div>
                </div>

                <div class="fields">

                    <div class="field">
                        <div class="ui form-wrap segment" style="display: grid">
                            <label><i class="info icon"></i>Description</label>
                            {{ form.text }}
                            <div class="muted">
                                {{ form.text.help_text }}
                            </div>
                        </div>
                    </div>

                </div>

                <button type="submit" class="ui submit green button">
                    <i class="save icon"></i>Submit
                </button>

                <a class="ui right floated button" href="{% url "user_profile" user.profile.uid %}">
                    <i class="undo icon"></i>Cancel
                </a>


            </form>
        </div>

        <div class="ui segment no-shadow"></div>
    </div>


{% endblock %}

schooloverflow/biostar/forum/templates/accounts/login.html
{% extends "forum_base.html" %}
{% load forum_tags %}
{% load socialaccount %}
{% block headtitle %}Login{% endblock %}

{% block content %}

    <form class="ui form" method="post" action="{% url 'login' %}">

        <div class="ui segment inputcolor socialbox">

            <div class="ui header">
                <i class="user icon"></i> Email Login
            </div>

            {% csrf_token %}

            {{ form.errors }}

            <div class="field">
                <label>Email</label>
                {{ form.email }}
            </div>

            <div class="field">
                <label>Password</label>
                {{ form.password }}
            </div>

            <div class="field">
                <button class="ui primary button" type="submit">
                    <i class="sign in icon"></i>Log In
                </button>

                <a class="ui right floated button" href="#" onclick="window.history.back()">
                    <i class="chevron left icon"></i>Back
                </a>
            </div>

        </div>


    </form>

    <div class="ui center aligned basic segment">


        <a href="{% url 'password_reset' %}"><i class="question circle icon"></i>Forgot your password?</a>
        &bull; <a class="" href="{% url 'signup' %}"><i class="add user icon"></i>Sign up with email</a>
    </div>




{% endblock %}

schooloverflow/biostar/forum/templates/accounts/logout.html
{% extends "forum_base.html" %}
{% load forum_tags %}
{% load accounts_tags %}

{% block headtitle %} Biostar Forum {% endblock %}
{% block title %} Log out {% endblock %}

{% block content %}

     <form method="post" action="{% url 'logout' %}" >

        <div class="ui center aligned header">

            <i class="sign out icon"></i>Do you want to log out?

        </div>
        <div class="ui centered card inputcolor">

            <div class="ui basic segment">
                    {% csrf_token %}
                    <button class="ui primary button" type="submit"> <i class="sign out icon"></i> Log out</button>
                    <a class="ui right floated  button" href="/"> <i class="home icon"></i>Home</a>
            </div>
        </div>
 </form>
{% endblock %}

schooloverflow/biostar/forum/templates/accounts/password_reset_complete.html
{% extends "forum_base.html" %}
{% block title %} Password Reset Complete{% endblock %}

{% block content %}

  <p class="ui center aligned basic segment">

    Your password has been reset. You may <a href="{% url 'login' %}">sign in</a> now.
  </p>

{% endblock %}

schooloverflow/biostar/forum/templates/accounts/password_reset_confirm.html
{% extends "forum_base.html" %}
{% block headtitle %} Reset Password {% endblock %}

{% block content %}


        <div class="ui center aligned header">

            <i class="user icon"></i>Change password

        </div>
         <div class="ui centered card inputcolor">

                {% if validlink %}

                    <form method="post" class="ui form attached fluid inputcolor segment" >
                        {% csrf_token %}
                        <div class="field">
                            <label>New Password</label>
                            {{ form.new_password1 }}
                        </div>

                        <div class="field">
                        <label>New Password Confirmation</label>
                        {{ form.new_password2 }}
                        </div>
                    <button class="ui primary button" type="submit">Change password</button>
                    </form>

                {% else %}
                    <p class="ui basic segment">

                        The password reset link was <b>invalid</b>.<br>
                        Please request a <a href="{% url 'password_reset' %}">new password reset link.</a>
                    </p>

                {% endif %}

        </div>

{%endblock%}

schooloverflow/biostar/forum/templates/accounts/password_reset_done.html
{% extends "forum_base.html" %}
{% block headtitle %}Reset Email Sent{% endblock %}

{% block content %}

    <p class="ui center aligned basic segment">

    We have emailed you instructions for setting your password, if an account exists with the email you entered.
    You should receive them shortly.
  </p>

    <p class="ui center aligned basic segment">

    If you don't receive an email, please make sure you've entered the address you registered with,
    and check your spam folder.
  </p>


{% endblock %}

schooloverflow/biostar/forum/templates/accounts/user_profile.html
{% extends "forum_base.html" %}
{% load accounts_tags %}
{% load forum_tags %}
{% block headtitle %}{{ target.profile.name }}{% endblock %}

{% block content %}

    <div class="ui stackable three column grid">

        <div class="column">


            <div class="ui center aligned  basic segment">
                <img class="ui centered circular image" src="{% gravatar user=target size=150 %}">
                <div class="ui centered header">
                    {{ target.profile.name }}
                    {% user_icon score=target.profile.score %}
                </div>
            </div>

            <div class="ui center aligned  basic segment">

                {% if target == request.user %}
                    <a class="ui mini button" href="{% url 'edit_profile' %}">
                        <i class="write icon"></i>Edit profile
                    </a>
                {% endif %}

                {% if can_moderate %}
                    <div class="ui mini button orange moderate-user" data-value="{{ target.id }}">
                        <i class="hand paper icon"></i>
                        Moderate
                    </div>
                {% endif %}

                {% if request.user.is_superuser and debugging %}
                    <a class="ui mini red button" href="{% url 'debug_user' %}?uid={{ target.profile.uid }}">
                        <i class="sign in icon"></i> Log in
                    </a>
                {% endif %}

            </div>

            <div class="moderate-insert" data-value="{{ target.id }}"></div>
        </div>

        <div class="column">


            <div class="ui center aligned basic segment">


                <table class="ui very basic table profile">
                    <tbody>

                    {% if target.profile.is_moderator %}
                        <tr>
                            <td>Role:</td>
                            <td>{{ target.profile.get_role_display }}</td>
                        </tr>
                    {% endif %}

                    <tr>
                        <td>Status:</td>
                        <td>{{ target.profile.get_state_display }}</td>
                    </tr>

                    <tr>
                        <td>Handle:</td>
                        <td><code>@{{ target.username }}</code></td>
                    </tr>

                    <tr>
                        <td>Reputation:</td>
                        <td>{{ target.profile.get_score }}</td>
                    </tr>

                    <tr>
                        <td>Email:</td>
                        <td>{{ target|show_email:request.user }}</td>
                    </tr>

                    <tr>
                        <td>Joined:</td>
                        <td>{{ target.profile.date_joined|time_ago }}</td>
                    </tr>

                    <!-- {% if target.profile.twitter %}
                        <tr>
                            <td>Twitter:</td>
                            <td>
                                <a href="https://twitter.com/{{ target.profile.twitter }}"><i
                                        class="twitter icon"></i>{{ target.profile.twitter }}</a>
                            </td>
                        </tr>
                    {% endif %} -->

                    <!-- {% if target.profile.scholar %}
                        <tr>
                            <td>Google Scholar:</td>
                            <td>
                                <a href="https://scholar.google.com/citations?user={{ target.profile.scholar }}"><i
                                        class="book icon"></i>{{ target.profile.scholar }}</a>
                            </td>
                        </tr>
                    {% endif %} -->
                    {% if target == request.user %}
                        <tr>
                            <td>Notifications:</td>
                            <td>{{ target.profile.get_message_prefs_display }}</td>
                        </tr>
                    {% endif %}

                    <tr>
                        <td>Last seen:</td>
                        <td>{{ target.profile.last_login |time_ago }}</td>
                    </tr>
                    {% if show_info %}
                        <tr>
                            <td>Location:</td>
                            <td>{{ target.profile.location }}</td>
                        </tr>
                    {% endif %}
                    </tbody>
                </table>

            </div>


        </div>
        <div class="column">
            <div class="profile ui relaxed divided list profile">

                <div class="item">
                    <div class="content">

                        {% if show_info %}
                            <p>{{ target.profile.html |safe }}</p>
                        {% else %}
                            <p>
                                Profile information, website and location are not shown for new users.
                            </p>
                            <p>
                                This helps us discourage the inappropriate use of our site.
                            </p>

                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="ui vertical segment">

        <div class="ui top attached tabular  menu">

            <a class="{% activate 'posts' active %}  item"
               href="{% url 'user_profile' target.profile.uid %}?active=posts">
                <i class="list alternate outline icon"></i><span class="phone"> Posts</span>
            </a>

            <a class="{% activate 'awards' active %}  item"
               href="{% url 'user_profile' target.profile.uid %}?active=awards">
                <i class="star outline icon"></i><span class="phone">Awards</span>
            </a>

        </div>
        <div class="ui bottom attached profile segment">
            {% if active == 'posts' %}
                {% list_posts target=target %}
            {% else %}
                {% list_awards target=target %}
            {% endif %}
        </div>
    </div>

{% endblock %}